name: Run Selenium Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual run from GitHub Actions tab

jobs:
  run_selenium:
    runs-on: ubuntu-latest  # Run on a Linux server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out code from repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium  # Install Selenium
    - name: Download Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1  # Install Chrome for headless mode

    - name: Run Selenium Script
      run: |
        python selenium_script.py  # Run the script
    - name: Commit and Push Output Files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add urls.txt
        git commit -m "Update output files [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
